// <auto-generated />
using System;
using FitWorld.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitWord.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231104223136_addPlans")]
    partial class addPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitWord.Models.Meal", b =>
                {
                    b.Property<int?>("mealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("mealId"));

                    b.Property<int?>("mealCarbs")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("mealDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("mealFat")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("mealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("mealProtein")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("mealId");

                    b.ToTable("Meal");

                    b.HasData(
                        new
                        {
                            mealId = 1,
                            mealCarbs = 15,
                            mealDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            mealFat = 15,
                            mealName = "poncho",
                            mealProtein = 15
                        },
                        new
                        {
                            mealId = 2,
                            mealCarbs = 15,
                            mealDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            mealFat = 15,
                            mealName = "flavor soup",
                            mealProtein = 15
                        },
                        new
                        {
                            mealId = 3,
                            mealCarbs = 15,
                            mealDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            mealFat = 15,
                            mealName = "chciken breast",
                            mealProtein = 15
                        });
                });

            modelBuilder.Entity("FitWord.Models.Plan", b =>
                {
                    b.Property<int>("planId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("planId"));

                    b.Property<int>("planDays")
                        .HasColumnType("int");

                    b.Property<string>("planDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("planLevel")
                        .HasColumnType("int");

                    b.Property<string>("planName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("planId");

                    b.ToTable("Plan");

                    b.HasData(
                        new
                        {
                            planId = 1,
                            planDays = 4,
                            planDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            planLevel = 0,
                            planName = "Push Pull"
                        },
                        new
                        {
                            planId = 2,
                            planDays = 4,
                            planDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            planLevel = 0,
                            planName = "Upper Lower"
                        },
                        new
                        {
                            planId = 3,
                            planDays = 4,
                            planDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            planLevel = 0,
                            planName = "Split"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
